#Database and SQL Final Project (Part 3)

##Name: 

**Make sure to "save" a copy of this file to your own account.**
**NOTE: Please include ALL of the parts of your final project (1, 2, and 3) for this submission, as this will be the last lab!**.

Exam 3 for the course will take the form of a “final project” where you will take a set of business rules (which you can find  below). and do the following.


1.	Formulate business rules
2.	Construct an ERD from a set of business rules
3.	Specify the relational schema
4.	Discuss whether this schema meets the 1N, 2N, and 3N normal forms
5.	Create the tables using SQL queries
6.	Run sample SQL queries that demonstrate your ability to
  
  a.	Create table with primary keys and multiple data types

  b.	Join tables with foreign keys

  c.	Insert sample data into tables

  d.	Update existing data in the table

  e.	Delete data from the table
7.	Run sample SQL queries that demonstrate your ability to do the following:

  a.	Simple single table queries

  b.	Single-table queries with WHERE and LIKE

  c.	Single-table queries with aggregate functions

  d.	Single table queries with GROUP BY

  e.	Single-table queries with HAVING

  f.	Subqueries

  g.	Simple multi-table queries with JOIN

  h.	More complex multi-table queries

  i.	The creation of table views
  
  j.	The creation of indexes
8.	Discuss your process of database design and implementation using the Software Development LifeCycle Model 
9.	Do something unique! You could do ONE of the following, or something else:

  a.	Build some indexes and analyze query performance

  b.	Figure out how to add a JSON column, and insert data

  c.	Write a PL/SQL functions or trigger and show how to use it

  d.	Expand the data model to include subtypes and supertypes

  e.	Let your creativity shine!
10.	Save this project as a portfolio-quality work to Github, which you can then share with me (and with future employers, if you would like).
The overall project is worth 100 points. We’ll be working on pieces of this for each of our “labs” from now until the end of the semester.


**Other Guidelines** Here are the guidelines for working on the project:

1. Each week, you should share your project with me to show me how you're doing. If you complete the required steps for that week, you'll receive full credit for the lab.
2. You are welcome to discuss your project with either me or your peers. However, your final work (for example, the ER diagram,  SQL code, etc.) should represent your *own* response. 
3. Each "step" in the lab will be worth ten points total (for a total of 100 points).

#Load Postgres (Run This Cell)

In [1]:
# Some UNIX utilites we need to install for the lab.
!pip install wget --quiet
!pip install sqlalchemy --quiet
!pip install ipython-sql --quiet

# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!pip install pgspecial --quiet

!sudo service postgresql start


# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

# Setup a postgres database with name `my_data` to be used
!sudo -u postgres psql -U postgres -c 'DROP DATABASE IF EXISTS my_data;'

!sudo -u postgres psql -U postgres -c 'CREATE DATABASE my_data;'

# Postgres variables
%env DB_NAME=my_data
%env DB_HOST=localhost
%env DB_PORT=5432
%env DB_USER=postgres
%env DB_PASS=postgres

# Finally, let's make a connnection with the databse
%load_ext sql
%sql postgresql://$DB_USER:$DB_PASS@$DB_HOST/$DB_NAME

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 10.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package cron.
(Reading database ... 155203 files and directories currently installed.)
Preparing to unpack .../0-cron_3.0pl1-128.1ubuntu1.1_amd64.deb ...
Unpacking cron (3.0pl1-128.1ubuntu1.1) ...
Selecting previously unselected package logrotate.
Preparing to unpack .../1-logrotate_3.11.0-0.1ubuntu1_amd64.deb ...
Unpacking logrotate (3.11.0-0.1ubuntu1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../2-netbase_5.4_all.deb ...
Unpacking netbase (5.4) ...
Selecting previously unselected

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


'Connected: postgres@my_data'

#Part 1: Scenario Analysis and Business Rule Formulation
For the project, you’ll be creating a mock database for “Monster University,” a school that takes young monsters (dragons, werewolves, cute “ET” style aliens, vampires, ogres, talking apes, robot assassins, and basically anything else you want) and teaches them to be upstanding members of the monster community. The professors are ALSO monsters. Here are the business rules you’ll need to get started:

1.	Your main goal is to represent the Monsters, Classes, and Locations (buildings/rooms) at the school.
2.	Monsters can either teach classes, take classes, or both.
3.	For all Monsters we need to keep track of their 

  a.	name

  b.	species (what kind of monster are they?)

  c.	date of birth

  d.	their diet, if known (herbivore, carnivore, omnivore, “brains”, “electricity”, etc.)

  e. their GPA (between 0 and 4.0)

  f. the number of credits completed.

4.	For classes, we’d like to track the following:

  a.	The title of the class

  b.	The location in which the class is held

  c.	The duration of the class in minutes (between 30 and 180)

  d.  The days on which the class meets (for example "MWF" or "TH").

  e.  The start time of the class 
  
  f.  The instructor of the class (who is a Monster)

  
5. For locations we want to record:

  a. A two-character building code (e.g., "MH" for Memorial Hall).

  b. The room number between 1 and 2000.

  c. The max capacity between 10 and 300.

6. Some Monsters are Alumni, who have graduated from the school. For alumni we also want to record:

  a. the year they graduated, and
  
  b. their degree (computer science, business, English, etc.).

7.	Formulate THREE additional business rules of your choice. Remember, you’ll eventually need to implement these! At least ONE of these rules should involve a new entity, relationship, and/or constraint (as opposed to simply a new attribute). 


##Your New Business Rules Here:
1. Buildings contain locations

2. buildings have name, buildingID, and room count

3. Teachers can teach multiple classes but a class can only have one teacher

#Part 2: Conceptual Modeling using Entity-Relationship Diagramming
In this step, I'd like to create an ERD for the business rules above using [Diagrams.net](https://diagrams.net). You should include all entities, attributes, relationships, and cardinalilities. After you have completed this diagram, you should do the following:

1. Export it as "SVG" file in diagrams.net, and save this to your computer.
2. Edit this cell, and select the "Insert Image" button.
3. Select the SVG file you download.
4. NOTE: SVG files will work much better than larger image files (which may cause problems if you try to insert them).

Final Part 1-Part 1.drawio.svg

#Part 3: Logical Modeling
In this part, I'd like you to map the E-R model you've created to a relational model. This involves creating a relational scheme like the following:


```
table_name_1(attribute1 (PK), attribute2, attribute3)
table_name_2(attribute1 (PK), attribute2, attribute3)

```
You should indicate any **primary keys** by using (PK) and any foreign keys with (FK). For primary keys, you'll need to think about whether you can/should use attributes included in the ER diagram, or whether you might want to to create new attributes to serve as keys.

I recommend creating entities in this order:
1. One table for each "strong" entity in the E-R diagram. Decide on a primary key.
2. Tables for subtypes, if needed.
3. One table for each "weak" entity (besides subtypes) in the E-R diagram. Decide on appropriate primary and foreign keys.
4. Tables needed to model M:N relationships present in the E-R diagram.

**PUT YOUR ANSWER BELOW.**

```
Monster(monsterID (PK), name, species, dob, diet, gpa, completedCredits, isTeacher)
Teacher(monsterID (PK))
Student(monsterID (PK))
Alumin(monsterID (PK), degree, graduationYear)
Classes(classID (PK), title, locationID (FK), duration, daysOfWeek, startTime, instructorID (FK))
Locations(roomID (PK), maxCapacity, buildingID (FK))
Building(buildingID (PK), name, roomCount)
```

#Part 4: Normalization
Are your relations normalized? Please provide a 2-3 sentence explanation of why/how they meet the following normal forms. Or, if they don't, describe what needs to be done to change them.

1. **First Normal Form.** 

Yes it is 1NF because none of the tables I have made will form new tables and none of them can be broken down into new tables.

2. **Second Normal Form.**

Yes it is in 2NF.  The reason is because each table has its own primary key that is not part of a candidate key.

3. **Third Normal Form.** 

Yes it meets 3NF

**Revised relational scheme (if needed):**
(Your answer here).


#Part 5: Creating Tables
In this part, you'll be creating the tables to store the data about your monstrous students. This involves "mapping" the relational schema to an actual Postgres Databases. Here's what you need to do:

1. CREATE a SQL table for each of the relations you identied in part 4.
2. Make sure all the attribututes are assigned appropriate data types. For example, INTEGER, VARCHAR, or DATE.
3.  Assign appropriate primary keys and foreign keys.

In the starter code below, I've assumed you'll have tables along the line of the following. However, you should feel free to rename, add, or delete tables as needed!

a. Monsters

b. Classes

c. Locations

d. Monsters2Classes

e. Alumni


In [6]:
%%sql

DROP TABLE IF EXISTS Monsters CASCADE;
DROP TABLE IF EXISTS Teacher CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS Alumni CASCADE;
DROP TABLE IF EXISTS Building CASCADE;
DROP TABLE IF EXISTS Locations CASCADE;
DROP TABLE IF EXISTS Classes CASCADE;
DROP TABLE IF EXISTS Monsters_Classes CASCADE;

 * postgresql://postgres:***@localhost/my_data
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.


[]

In [7]:
%%sql

CREATE TABLE Monsters(
  monsterID INT NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  species VARCHAR(255), 
  dob DATE CHECK (dob < NOW()) NOT NULL,
  diet VARCHAR(255), 
  gpa DECIMAL(3, 2), 
  completedCredits INT,
  isTeacher BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (monsterID)
);

CREATE TABLE Teacher(
  teacherID INT NOT NULL UNIQUE,
  monsterID INT NOT NULL,
  PRIMARY KEY (teacherID),
  FOREIGN KEY (monsterID) REFERENCES Monsters(monsterID)
);

CREATE TABLE Student(
  studentID INT NOT NULL UNIQUE,
  monsterID INT NOT NULL,
  PRIMARY KEY (studentID),
  FOREIGN KEY (monsterID) REFERENCES Monsters(monsterID)
);

CREATE TABLE Alumni(
  alumniID INT NOT NULL UNIQUE,
  monsterID INT NOT NULL,
  degree VARCHAR(255),
  gradYear SMALLINT,
  PRIMARY KEY (alumniID),
  FOREIGN KEY (monsterID) REFERENCES Monsters(monsterID)
);

CREATE TABLE Building(
  buildingID INT NOT NULL UNIQUE,
  name VARCHAR(255),
  buildingCodeName VARCHAR(255),
  roomCount INT,
  PRIMARY KEY (buildingID)
);

CREATE TABLE Locations(
  roomID INT NOT NULL UNIQUE,
  buildingID INT NOT NULL,
  maxCapacity INT NOT NULL,
  PRIMARY KEY (roomID),
  FOREIGN KEY (buildingID) REFERENCES Building(buildingID)
);

CREATE TABLE Classes(
  classID INT NOT NULL UNIQUE,
  locationID INT,
  buildingID INT,
  instructorID INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  duration SMALLINT NOT NULL,
  daysOfWeek VARCHAR(255) NOT NULL,
  startTime TIME NOT  NULL,
  PRIMARY KEY (classID),
  FOREIGN KEY (locationID) REFERENCES Locations(roomID),
  FOREIGN KEY (buildingID) REFERENCES Building(buildingID),
  FOREIGN KEY (instructorID) REFERENCES Teacher(teacherID)
);

CREATE TABLE Monsters_Classes(
  classID INT NOT NULL,
  monsterID INT NOT NULL,
  FOREIGN KEY (ClassID) REFERENCES Classes(ClassID),
  FOREIGN KEY (monsterID) REFERENCES Monsters(monsterID),
  PRIMARY KEY (classID, monsterID)
);

 * postgresql://postgres:***@localhost/my_data
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.


[]

#Part 6: Retrieving, Updating, and Deleting Data
In this part, you'll be inserting some data about Monsters, Classes, and Locations.


##6b. Inserting Data
Here are five monsters to insert your database:

1. Cookie Monster (unknown species) was born on Nov 10, 1969. His eats only cookies. He has 3.2 GPA and has completed 76 credits.
2. Marceline (vampire) was born in Feb 3, 1056. She eats "the color red". She is a teacher with a 0.0 GPA and 0 credits completed.
3. Chewbacca (wookie) was born on May 25, 1977. He is an omnivore. He has a 2.6 GPA and has completed 24 credits.
4. Dracula (vampire) was born on Aug 15, 1543. He drinks blood. He has a 4.0 GPA with 112 credits completed. He also teachers classes.
5. Maleficient (dragon) was born on Oct 26, 1856. She is a carnviore. She has a 3.8 GPA with 63 credits completed.
6. Insert at least FOUR more monsters of your choice. At least two of these should have the same species.

Now, show the data in the table.

Here are three locations to insert into your database:
1. CL 101 ("Castle level 1, room 1") holds 100 people.
2. CL 503 ("Castle level 5, room 3") holds 34 people.
3. MU 220 ("Monster Union room 220") holds 12 people.
4. Insert at least TWO more locations into your database. Both should be in the same building. 

Now, show the data in the table.


Here are two classes to insert into your database:
1. Marceline teaches Intro to Guitar on TH from 2 PM to 4 PM in MU 220.
2. Dracula teaches Monster First Aid on MWF from 9 PM to 10 PM.
2. Insert at least ONE more class.

Now, show the data in the table.


"ENROLL" some students in your classes.
1. Cookie Monster, Chewbacca, Dracula, and Maleficient (and perhaps some of the students you added) will take Monster First Aid.
2. Chewbacca and Malificient (and perhaps some of the students you added) will take Intro to Guitar.
3. Enroll some students in your own class!
Now, show the data in the table.


Finally, insert data for at least ONE alumni, and show the results.

In [8]:
%%sql

DELETE FROM Monsters_Classes CASCADE;
DELETE FROM Classes CASCADE;
DELETE FROM Locations CASCADE;
DELETE FROM Teacher CASCADE;
DELETE FROM Student CASCADE;
DELETE FROM Alumni CASCADE;
DELETE FROM Building CASCADE;
DELETE FROM Monsters CASCADE;

 * postgresql://postgres:***@localhost/my_data
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.


[]

In [9]:
%%sql

INSERT INTO Monsters (monsterID, name, species, dob, diet, gpa, completedCredits, isTeacher)
VALUES 
  (1, 'Cookie Monster', null, '1969-11-10', 'Cookies', 3.2, 75, FALSE),
  (2, 'Marceline', 'Vampire', '1056-02-02', 'The Color Red', 0.0, 0, TRUE),
  (3, 'Chewbacca', 'Wookie', '1977-05-25', 'Omnivore', 2.6, 24, FALSE),
  (4, 'Dracula', 'Vampire', '1543-07-15', 'Blood', 4.0, 112, TRUE),
  (5, 'Maleficient', 'Dragon', '1856-09-26', 'Carnivore', 3.8, 63, FALSE),
  (6, 'Shrek', 'Ogre', '1999-02-27', 'Anything', 2.4, 27, TRUE),
  (7, 'Kraken', 'Seamonster', '1986-04-22', 'Carnivore', 0.0, 0, FALSE),
  (8, 'Godzilla', 'Seamonster', '1954-11-03', 'Fairy Dust', 4.5, 75, FALSE),
  (9, 'Siren Head', null, '1987-06-24', null, 0.0, 0, FALSE),
  (10, 'Garduated Test', null, '1999-01-01', null, null, null, FALSE);

INSERT INTO Teacher (teacherID, monsterID)
VALUES
  (1, 4),
  (2, 2),
  (3, 6);

INSERT INTO Student (studentID, monsterID)
VALUES
  (1, 1),
  (2, 3),
  (3, 5),
  (4, 7),
  (5, 8);

INSERT INTO Alumni (alumniID, monsterID, degree, gradYear)
VALUES
  (1, 10, 'Computer Science', 2022);

INSERT INTO Building (buildingID, name, buildingCodeName, roomCount)
VALUES
  (1, 'Castle', 'CL', 67),
  (2, 'Monster Union', 'MU', 16),
  (3, 'Scare School', 'SS', 90);

INSERT INTO Locations (roomID, buildingID, maxCapacity)
VALUES
  (101, 1, 100),
  (503, 1, 34),
  (220, 2, 12),
  (146, 3, 75),
  (246, 3, 75);

INSERT INTO Classes (classID, locationID, buildingID, instructorID, title, duration, daysOfWeek, startTime)
VALUES
  (1, 220, 2, 1, 'Intro to Guitar', 120, 'TH', '14:00:00'),
  (2, NULL, NULL, 2, 'Monster First Aid', 60, 'MWF', '21:00:00'),
  (3, 146, 3, 3, 'Swamp Survival', 180, 'MTWTHF', '06:00:00');

INSERT INTO Monsters_Classes (classID, monsterID)
VALUES
  (1, 1),
  (1, 3),
  (1, 4),
  (1, 5),
  (2, 3),
  (2, 5),
  (3, 3),
  (3, 7),
  (3, 8),
  (3, 9);

 * postgresql://postgres:***@localhost/my_data
10 rows affected.
3 rows affected.
5 rows affected.
1 rows affected.
3 rows affected.
5 rows affected.
3 rows affected.
10 rows affected.


[]

In [10]:
%%sql
SELECT * FROM Monsters;

 * postgresql://postgres:***@localhost/my_data
10 rows affected.


[(1, 'Cookie Monster', None, datetime.date(1969, 11, 10), 'Cookies', Decimal('3.20'), 75, False),
 (2, 'Marceline', 'Vampire', datetime.date(1056, 2, 2), 'The Color Red', Decimal('0.00'), 0, True),
 (3, 'Chewbacca', 'Wookie', datetime.date(1977, 5, 25), 'Omnivore', Decimal('2.60'), 24, False),
 (4, 'Dracula', 'Vampire', datetime.date(1543, 7, 15), 'Blood', Decimal('4.00'), 112, True),
 (5, 'Maleficient', 'Dragon', datetime.date(1856, 9, 26), 'Carnivore', Decimal('3.80'), 63, False),
 (6, 'Shrek', 'Ogre', datetime.date(1999, 2, 27), 'Anything', Decimal('2.40'), 27, True),
 (7, 'Kraken', 'Seamonster', datetime.date(1986, 4, 22), 'Carnivore', Decimal('0.00'), 0, False),
 (8, 'Godzilla', 'Seamonster', datetime.date(1954, 11, 3), 'Fairy Dust', Decimal('4.50'), 75, False),
 (9, 'Siren Head', None, datetime.date(1987, 6, 24), None, Decimal('0.00'), 0, False),
 (10, 'Garduated Test', None, datetime.date(1999, 1, 1), None, None, None, False)]

In [11]:
%%sql
SELECT * FROM Classes;

 * postgresql://postgres:***@localhost/my_data
3 rows affected.


[(1, 220, 2, 1, 'Intro to Guitar', 120, 'TH', datetime.time(14, 0)),
 (2, None, None, 2, 'Monster First Aid', 60, 'MWF', datetime.time(21, 0)),
 (3, 146, 3, 3, 'Swamp Survival', 180, 'MTWTHF', datetime.time(6, 0))]

In [12]:
%%sql
SELECT * FROM Teacher;

 * postgresql://postgres:***@localhost/my_data
3 rows affected.


[(1, 4), (2, 2), (3, 6)]

In [13]:
%%sql
SELECT * FROM Student;

 * postgresql://postgres:***@localhost/my_data
5 rows affected.


[(1, 1), (2, 3), (3, 5), (4, 7), (5, 8)]

In [14]:
%%sql
SELECT * FROM Building;

 * postgresql://postgres:***@localhost/my_data
3 rows affected.


[(1, 'Castle', 'CL', 67),
 (2, 'Monster Union', 'MU', 16),
 (3, 'Scare School', 'SS', 90)]

In [15]:
%%sql
SELECT * FROM Alumni;

 * postgresql://postgres:***@localhost/my_data
1 rows affected.


[(1, 10, 'Computer Science', 2022)]

In [16]:
%%sql
SELECT * FROM Monsters_Classes;

 * postgresql://postgres:***@localhost/my_data
10 rows affected.


[(1, 1),
 (1, 3),
 (1, 4),
 (1, 5),
 (2, 3),
 (2, 5),
 (3, 3),
 (3, 7),
 (3, 8),
 (3, 9)]

In [17]:
%%sql
SELECT * FROM Locations;

 * postgresql://postgres:***@localhost/my_data
5 rows affected.


[(101, 1, 100), (503, 1, 34), (220, 2, 12), (146, 3, 75), (246, 3, 75)]

#6c: Updating Data
In this section, I'd like you to run the following updates

1. MU 220 has been expanded! It can now hold 25 students, instead of 12.
2. Another semester has passed. Add 12 credits to each student's record.
3. [Another update of your choice--describe here.]

After each update please SELECT from the table to show the results.

In [18]:
%%sql
--Update MU 220 and show results

UPDATE Locations
SET maxCapacity = 25
WHERE roomID = 220;

SELECT * FROM Locations

 * postgresql://postgres:***@localhost/my_data
1 rows affected.
5 rows affected.


[(101, 1, 100), (503, 1, 34), (146, 3, 75), (246, 3, 75), (220, 2, 25)]

In [19]:
%%sql 
--Update student credits and show results

UPDATE Monsters
SET completedCredits = completedCredits + 12
WHERE monsterID >= 0;

SELECT * FROM Monsters

 * postgresql://postgres:***@localhost/my_data
10 rows affected.
10 rows affected.


[(1, 'Cookie Monster', None, datetime.date(1969, 11, 10), 'Cookies', Decimal('3.20'), 87, False),
 (2, 'Marceline', 'Vampire', datetime.date(1056, 2, 2), 'The Color Red', Decimal('0.00'), 12, True),
 (3, 'Chewbacca', 'Wookie', datetime.date(1977, 5, 25), 'Omnivore', Decimal('2.60'), 36, False),
 (4, 'Dracula', 'Vampire', datetime.date(1543, 7, 15), 'Blood', Decimal('4.00'), 124, True),
 (5, 'Maleficient', 'Dragon', datetime.date(1856, 9, 26), 'Carnivore', Decimal('3.80'), 75, False),
 (6, 'Shrek', 'Ogre', datetime.date(1999, 2, 27), 'Anything', Decimal('2.40'), 39, True),
 (7, 'Kraken', 'Seamonster', datetime.date(1986, 4, 22), 'Carnivore', Decimal('0.00'), 12, False),
 (8, 'Godzilla', 'Seamonster', datetime.date(1954, 11, 3), 'Fairy Dust', Decimal('4.50'), 87, False),
 (9, 'Siren Head', None, datetime.date(1987, 6, 24), None, Decimal('0.00'), 12, False),
 (10, 'Garduated Test', None, datetime.date(1999, 1, 1), None, None, None, False)]

In [20]:
%%sql 
--Swamp Survival is no longer happening on Thursdays 

UPDATE Classes
SET daysOfWEEK = 'MTWF'
WHERE classID = 3;

SELECT * FROM Classes

 * postgresql://postgres:***@localhost/my_data
1 rows affected.
3 rows affected.


[(1, 220, 2, 1, 'Intro to Guitar', 120, 'TH', datetime.time(14, 0)),
 (2, None, None, 2, 'Monster First Aid', 60, 'MWF', datetime.time(21, 0)),
 (3, 146, 3, 3, 'Swamp Survival', 180, 'MTWF', datetime.time(6, 0))]

#Part 7: SQL Queries
In this section, you'll be demonstrating your ability to retrieve data from the database you've created using SQL queries. 

##7a: Simple Single table queries
Retreive a list of monsters ordered alphabetically by name. Limit your results to 5.

In [21]:
%%sql
-- 7a

SELECT * FROM Monsters
ORDER BY name ASC
LIMIT 5;

 * postgresql://postgres:***@localhost/my_data
5 rows affected.


[(3, 'Chewbacca', 'Wookie', datetime.date(1977, 5, 25), 'Omnivore', Decimal('2.60'), 36, False),
 (1, 'Cookie Monster', None, datetime.date(1969, 11, 10), 'Cookies', Decimal('3.20'), 87, False),
 (4, 'Dracula', 'Vampire', datetime.date(1543, 7, 15), 'Blood', Decimal('4.00'), 124, True),
 (10, 'Garduated Test', None, datetime.date(1999, 1, 1), None, None, None, False),
 (8, 'Godzilla', 'Seamonster', datetime.date(1954, 11, 3), 'Fairy Dust', Decimal('4.50'), 87, False)]

##7b. Single-table queries with WHERE and LIKE
Retrieve JUST the classes that meet on Wednesday (where Wednesday is the 'W' in strings like 'MWF').

In [22]:
%%sql
-- 7b

SELECT * FROM Classes
WHERE daysOfWeek LIKE '%W%';

 * postgresql://postgres:***@localhost/my_data
2 rows affected.


[(2, None, None, 2, 'Monster First Aid', 60, 'MWF', datetime.time(21, 0)),
 (3, 146, 3, 3, 'Swamp Survival', 180, 'MTWF', datetime.time(6, 0))]

##7c. Single-table queries with aggregate functions
Retrieve the minimum, maximum, and average GPA included in your database. You should label the columns "Min GPA", "Max GPA", and "Avg GPA".

In [23]:
%%sql 
--7c

SELECT ROUND(AVG(GPA), 2) AS "Avg GPA", MIN(GPA) AS "Min GPA", MAX(GPA) AS "Max GPA" FROM Monsters;

 * postgresql://postgres:***@localhost/my_data
1 rows affected.


[(Decimal('2.28'), Decimal('0.00'), Decimal('4.50'))]

##7d. Single table queries with GROUP BY
Retrieve a list of each monster species included in the database, along with a count of how many monsters are members of the species.

In [24]:
%%sql
--7d

SELECT species, Count(monsterID) FROM Monsters
GROUP BY species;

 * postgresql://postgres:***@localhost/my_data
6 rows affected.


[(None, 3),
 ('Dragon', 1),
 ('Vampire', 2),
 ('Ogre', 1),
 ('Wookie', 1),
 ('Seamonster', 2)]

##7e. Single-table queries with HAVING
Retrieve a list of the buildings (not rooms!) in your data that have a total capacity of more than 20. (A building's capacity is simply the sum of the capacities of all the classrooms it contains).

In [25]:
%%sql
--7e

SELECT Building.name, SUM(maxCapacity) FROM Locations
JOIN Building
ON Locations.buildingID = Building.buildingID
GROUP BY Building.buildingID
HAVING SUM(maxCapacity) >= 20;

 * postgresql://postgres:***@localhost/my_data
3 rows affected.


[('Monster Union', 25), ('Scare School', 150), ('Castle', 134)]

##7f. Subqueries
Retrieve a list of monsters names and species, together with a count of how many members of that species are in the database.

In [26]:
%%sql
-- 7f

SELECT name, species,(SELECT Count(species) FROM Monsters M2 WHERE M.species = M2.species) FROM Monsters M


 * postgresql://postgres:***@localhost/my_data
10 rows affected.


[('Cookie Monster', None, 0),
 ('Marceline', 'Vampire', 2),
 ('Chewbacca', 'Wookie', 1),
 ('Dracula', 'Vampire', 2),
 ('Maleficient', 'Dragon', 1),
 ('Shrek', 'Ogre', 1),
 ('Kraken', 'Seamonster', 2),
 ('Godzilla', 'Seamonster', 2),
 ('Siren Head', None, 0),
 ('Garduated Test', None, 0)]

#7g. Simple multi-table queries with JOIN
Retrieve the names and GPAs of students enrolled in Intro to Guitar.

In [27]:
%%sql
-- 7g

SELECT name, GPA FROM Monsters M
INNER JOIN Monsters_Classes MC
ON M.monsterID = MC.monsterID
INNER JOIN Classes C
ON MC.classID = C.classID
WHERE C.title LIKE 'Intro to Guitar'

 * postgresql://postgres:***@localhost/my_data
4 rows affected.


[('Cookie Monster', Decimal('3.20')),
 ('Chewbacca', Decimal('2.60')),
 ('Dracula', Decimal('4.00')),
 ('Maleficient', Decimal('3.80'))]

##7h. More complex multi-table queries
Retrieve the total students taught by each teacher in the database. You should have one row of output for each teacher with their name and the total number of students.

In [33]:
%%sql 
-- 7h

SELECT teacherID, name, (SELECT COUNT(ClassID) FROM Monsters_Classes MC2 WHERE T.teacherID = C.instructorID AND MC2.classID = C.classID) FROM Monsters M
LEFT JOIN Monsters_Classes MC
ON M.monsterID = MC.monsterID
LEFT JOIN Classes C
ON MC.classID = C.classID
LEFT JOIN Teacher T
ON M.monsterID = T.monsterID
WHERE isTeacher = TRUE

 * postgresql://postgres:***@localhost/my_data
3 rows affected.


[(2, 'Marceline', 0), (1, 'Dracula', 4), (3, 'Shrek', 0)]

##7i. Creation of Views
Create a VIEW based on a SQL query of your choice. Now "SELECT *" from this view to show the results.

In [29]:
%%sql
-- 7i

--DROP VIEW test;

CREATE VIEW test AS
SELECT B.name, B.buildingCodeName, L.roomID FROM Building B
LEFT JOIN Locations L 
ON B.buildingID = L.buildingID;

SELECT * FROM test;

 * postgresql://postgres:***@localhost/my_data
Done.
5 rows affected.


[('Castle', 'CL', 101),
 ('Castle', 'CL', 503),
 ('Scare School', 'SS', 146),
 ('Scare School', 'SS', 246),
 ('Monster Union', 'MU', 220)]

##7g. Creation of Indexes.
Create an index on the column that contains the Monster's names. 

In [30]:
%%sql
-- 7f

CREATE INDEX MonsterNames
ON Monsters (name);

 * postgresql://postgres:***@localhost/my_data
Done.


[]

#8. Database Design Philosophy
In 150 to 200 words, answer the question **"What are the keys to designing a successful database, and how is this reflected in your own work here?"**

  To me there are many keys to designing a successful database.  One of these ways is by making a detailed and well thought out ER diagram.  The reason for this is because ethe better your ER diagram, the easier it will be for you to do normalization on your database and then make it even easier for you to actually code in your tables.  This is shown in my database by how I thought-out my relationships, tables, and attributes.  Another key to designing a successful database is testing it with potential real-world queries and examples.  For example, with this project after designing the database you tasked us with doing some test queries to test us.  But at the same time, we are testing out database and from there we are changing attributes and tables to make it work better in the real world.  The final thing I'll mention is doing normalization steps to the best extent.  By doing it fully it helps to work out flaws and redundencies and make your database better before implemtning it.

#9. Be Creative!
In 150 to 200 words, tell me about what you've done (or will do, in this section) that goes above and beyond the "requirements" of the assignment. Why did you choose to do this? What did you learn from doing it?

I feel something I did that goes above and beyond is by adding the Building table.  The way it went above and beyond to me is that it changed the way I had to do the queries you asked me to do.  The reason I had to do them differently than if I didn't make a table for Buildings is because the Buildings data would of been partially stored in the Locations table and when doing a query I would of only needed to call the Locations table.  But instead I had to use a join to join Locations to Building and the SELECT the columns I needed form the new table I made.  The final thing I think I did that goes above and beyond is 

In [ ]:
%%sql
-- Include code, if needed.

#10. Share Work With Me on Github
Finally, I'd like you to share your work with me on Github. If you are interesting in working in computer science or IT, it's good to have a basic understanding of how Github works, as its something like an industry "standard" way of sharing code. 
 
Here's what you need to do:
1. Create an account on https://github.com/ 
2. Create a PUBLIC repository called "database_sql".
3. Save your **completed** lab to this repository. From colab, all you need to do is go to "File: Save a copy in Github."

An in-depth tutorial on using Github is here:
https://docs.github.com/en/get-started/quickstart/hello-world 
The only things you need to worry about are (a) creating an account and (b) creating a repository. We won't be worry about branches, commits, or pulls (though you are free to read up on these!). 

Once you've done this, please write down your:

USERNAME: 

REPOSITORY LINK:

And that's it! I've enjoyed having you in class--enjoy the rest of the semster :).

**You should also submit this to the D2L Assignment folder.**